### ISSUE TITLE
Files parsing 

### ISSUE THREAD

**Issue by meytan** [BombelkiIOIO/IO1#5]

**Comment by dmichig** [comment]
Funkcja, po podaniu nazwy pliku, zwraca ew. tworzy obiekt i ustawia wartości jego zmiennych (np tablica, słownik itp. itd.) nazwy plików od których zależy analizowany plik z kodem oraz ilość wystąpień (wywołań funkcji, użycia zmiennych itp. z pliku "dołączanego").
